<?php
/**
 *  File generated by Skyline CMS Compiler
 *  (c) Skyline CMS by TASoft Applications
 *  All rights reserved
 *  @license BSD-3-Clause
 */
 
 return array (
  'tasoft/collection' => 'vendor/tasoft/collection/composer.json',
  'tasoft/event-manager' => 'vendor/tasoft/event-manager/composer.json',
  'tasoft/method-signature' => 'vendor/tasoft/method-signature/composer.json',
  'tasoft/service-manager' => 'vendor/tasoft/service-manager/composer.json',
  'tasoft/config' => 'vendor/tasoft/config/composer.json',
  'tasoft/dependency-injection' => 'vendor/tasoft/dependency-injection/composer.json',
  'tasoft/tools-path' => 'vendor/tasoft/tools-path/composer.json',
  'symfony/deprecation-contracts' => 'vendor/symfony/deprecation-contracts/composer.json',
  'symfony/polyfill-mbstring' => 'vendor/symfony/polyfill-mbstring/composer.json',
  'symfony/polyfill-php83' => 'vendor/symfony/polyfill-php83/composer.json',
  'symfony/http-foundation' => 'vendor/symfony/http-foundation/composer.json',
  'skyline/kernel' => 'vendor/skyline/kernel/composer.json',
  'skyline/router' => 'vendor/skyline/router/composer.json',
  'skyline/exposed-symbols' => 'vendor/skyline/exposed-symbols/composer.json',
  'skyline/render' => 'vendor/skyline/render/composer.json',
  'skyline/core-application' => 'vendor/skyline/core-application/composer.json',
  'skyline/html-elements' => 'vendor/skyline/html-elements/composer.json',
  'tasoft/mime' => 'vendor/tasoft/mime/composer.json',
  'skyline/direct-components' => 'vendor/skyline/direct-components/composer.json',
  'tasoft/php-string-parser' => 'vendor/tasoft/php-string-parser/composer.json',
  'skyline/html-render' => 'vendor/skyline/html-render/composer.json',
  'tasoft/menu-service' => 'vendor/tasoft/menu-service/composer.json',
  'skyline/navigation' => 'vendor/skyline/navigation/composer.json',
  'skyline/cms' => 'vendor/skyline/cms/composer.json',
  'wlw/kleinteilelager' => './',
  'symfony/polyfill-ctype' => 'vendor/symfony/polyfill-ctype/composer.json',
  'symfony/filesystem' => 'vendor/symfony/filesystem/composer.json',
  'skyline/compiler' => 'vendor/skyline/compiler/composer.json',
  'skyline/route-annotation-compiler' => 'vendor/skyline/route-annotation-compiler/composer.json',
  'skyline/binary' => 'vendor/skyline/binary/composer.json',
  'skyline/api' => 'vendor/skyline/api/composer.json',
  'skyline/component-skyline' => 'vendor/skyline/component-skyline/composer.json',
  'skyline/component-api' => 'vendor/skyline/component-api/composer.json',
  'skyline/html-form' => 'vendor/skyline/html-form/composer.json',
  'skyline/component-bootstrap' => 'vendor/skyline/component-bootstrap/composer.json',
);