<?php

use Skyline\Render\Context\DefaultRenderContext;
/**
 * @title WLW Projekt :: Home
 * @description WLW Projekt :: Kleinteilelager
 * @require Application
 *
 * @var DefaultRenderContext $this
 */

?>
<div class="content">
	<div >
        Resourcen Felder:
        <ul>
            <li>Name</li>
            <li>Beschreibung</li>
            <li>Keywords</li>
            <li>Bestand</li>
            <li>Lagerort</li>
        </ul>
    </div>
</div>
