<?php

use Skyline\Render\Context\DefaultRenderContext;
/**
 * @title Home
 * @description Hello, world!
 * @require Application
 *
 * @var DefaultRenderContext $this
 */

?>
<style type="text/css">
	#my-header {
		display: none;
	}
</style>
<div class="content">
	<div >
        Resourcen Felder:
        <ul>
            <li>Name</li>
            <li>Beschreibung</li>
            <li>Keywords</li>
            <li>Bestand</li>
            <li>Lagerort</li>
        </ul>
    </div>
</div>
