<?php

use Skyline\Render\Context\DefaultRenderContext;
/**
 * @title WLW Projekt :: Home
 * @description WLW Projekt :: Kleinteilelager
 * @require Application
 *
 * @var DefaultRenderContext $this
 * @var Generator $LAGERORTE
 */

?>
<link href="/Public/css/tabelle.css" rel="stylesheet" media="all">
<script src="/Public/js/tabelle.js" type="application/javascript"></script>

<script type="application/javascript">

</script>

<div class="content">
	<h1>Material</h1>

    <table class="table table-sm table-striped table-hover" id="tbl-material">
        <thead>
        <tr>
            <th data-ref="name" class="sortable">Material</th>
            <th data-ref="description">Beschreibung</th>
            <th data-ref="lager">Lagerort</th>
            <th data-ref="bestand">Bestand</th>
            <th> </th>
        </tr>
        </thead>
        <tbody>
        <tr class="template">
            <td data-ref="name">Schraube M3x15mm</td>
            <td data-ref="description" class="info">DIN 912 Zylinderschrauben mit Innensechskant; ISO 4762 modifiziert [Norm zurückgezogen] 912</td>
            <td data-ref="lager">Lager 13</td>
            <td data-ref="bestand">38</td>
            <td class="mat-tools">
                <button data-action="buchen" class="mat-buchen btn btn-sm btn-outline-success p-0 px-2">Buchen</button>
                <button data-action="delete" class="mat-delete btn btn-sm btn-outline-danger p-0 px-2">Löschen</button>
                <button data-action="edit" class="mat-edit btn btn-sm btn-outline-primary p-0 px-2">Ändern</button>
            </td>
        </tr>
        </tbody>
        <tfoot >
        <tr style="background-color: #f3f4ee">
            <td colspan="100">
                <div class="row align-items-center border-top pt-1">
                    <div class="col-auto">
                        <div class="input-group input-group-sm mb-3">
                            <span class="input-group-text page-move first" data-page="1">«</span>
                            <span class="input-group-text page-move prev" data-page="1">&lt</span>
                            <input type="text" placeholder="2 / 29" style="width: 80px; flex: none" data-page="1" class="form-control text-center page-counter" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                            <span class="input-group-text page-move next" data-page="2">&gt;</span>
                            <span class="input-group-text page-move last" data-page="0">»</span>
                        </div>
                    </div>

                    <div class="col-auto">
                        <div class="input-group input-group-sm mb-3 ms-4">
                            <label class="col-form-label-sm">Datensätze pro Seite</label>
                        </div>
                    </div>

                    <div class="col-auto">
                        <div class="input-group input-group-sm mb-3">
                            <select class="form-select page-count">
                                <option selected>10</option>
                                <option>25</option>
                                <option>50</option>
                                <option>100</option>
                                <option>250</option>
                                <option>500</option>
                                <option>1000</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-auto ms-auto">
                        <div class="input-group input-group-sm mb-3">
                            <label class="col-form-label-sm total-marker">0 - 0 / 0</label>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        </tfoot>
    </table>
    <button class="mat-add btn btn-sm btn-outline-success p-0 px-2" onclick="add_new_material()">Neues Material Erfassen</button>
</div>

<script type="text/javascript">
    const TABELLE = new OrganisierteTabelle('tbl-material');

    // Spezielle Anpassungen
    TABELLE.formatValue = function(name, value) {
        if(name === 'lager') {
            const list = $.map(value[name], l => {
                return l.name;
            });
            if(list.length > 1)
                list.push(`<hr class="p-0 m-0"><b>Total ${list.length}</b>`)
            return list.join("<br>");
        }
        if(name === 'bestand') {
            let summe = 0;
            const list = $.map(value['lager'], l => {
                summe += l.bestand;
                return l.bestand;
            });
            if(list.length > 1)
                list.push(`<hr class="p-0 m-0"><b>${summe}</b>`)
            return list.join("<br>");
        }

        if(value.hasOwnProperty(name))
            return value[name];
        return "??";
    }

    const fetch_material = (list) => {
        TABELLE.clearData();

        for(const idx in list) {
            Skyline.API.get("material-fetch?material_id="+list[idx])
                .success(data => {
                    if(data.hasOwnProperty("material")) {
                        TABELLE.insertDataRow(list[idx], data.material);
                    }
                })

        }
    }


    const my_table_content_loader = () => {
        Skyline.API.get("material-list?")
            .success(data=>{
                if(data.hasOwnProperty("list")) {
                    fetch_material(data.list)
                    TABELLE.parsePageLocationResponse(data);
                }
            })
    }

    $(()=>{
        my_table_content_loader();
    })

    TABELLE.on("buttonclicked", (params) => {
        const {action, id, data} = params;
        if(action === 'delete') {
            if(confirm("Willst du das Material «"+data.name+"» wirklich löschen?")) {
                Skyline.API.get("material-delete?material_id="+id)
                    .success(()=>{
                        my_table_content_loader();
                    })
                    .error(err => console.error(err));
            }
        } else if(action === 'edit') {
            $("#modal-title").text("Material Bearbeiten")
            $("#modal-edit").modal("show");

            const $lname = $("#lname").val( data.name );
            $("#material_id").val( id )
            $("#ldesc").val( data.description );
            $("#keywords").val( "" );

            Skyline.API.get("material-keywords-list?material_id="+id)
                .success(d => {
                    $("#keywords").val( d.keywords.join(" ") );
                });

            window.setTimeout(()=> {
                $lname.focus();
            }, 500 );
        } else if(action === 'buchen') {
            $("#modal-buchen").modal("show");
            $("#bname").val( data.name );
            $("#bmaterial_id").val( id )

            $("#blager").val(0);
            $("#bcount").val("");
        }
    })

    function add_new_material() {
        $("#modal-title").text("Neues Material anlegen")
        $("#modal-edit").modal("show");
        const $lname = $("#lname").val( "" );
        $("#material_id").val( 0 )
        $("#ldesc").val( "" );
        $("#keywords").val( "" );

        window.setTimeout(()=> {
            $lname.focus();
        }, 500 );
    }

    function send_material_changes(frm) {
        const fd = new FormData(frm);

        const material_id = frm['material_id'].value;

        const add_keywords = (mid) => {
            const words = $("#keywords").val().split(/[\s,]+/i);

            for(const idx in words) {
                Skyline.API.get("material-keyword-add?material_id="+mid+"&keyword="+encodeURI( words[idx] ))
            }
        }

        if(material_id > 0) {
            Skyline.API.post("material-change?material_id="+material_id, fd)
                .success(d => {
                    my_table_content_loader();
                    Skyline.API.get("material-keyword-clear?material_id="+material_id)
                        .success(d => {
                            add_keywords(material_id);
                        })
                })
                .error(err => console.error(err))
                .done(()=>{
                    $("#modal-edit").modal("hide");
                })
        } else {
            Skyline.API.post("material-add", fd)
                .success(d => {
                    const mat_id = d.material_id;
                    if(mat_id) {
                        add_keywords(mat_id);
                    }
                    my_table_content_loader();
                })
                .error(err => console.error(err))
                .done(()=>{
                    $("#modal-edit").modal("hide");
                })
        }

        return false;
    }

    function send_material_buchen(frm) {
        const fd = new FormData();

        const count = $("#bcount").val();
        const material_id = $("#bmaterial_id").val();

        if(material_id && count > 0 || count < 0) {
            fd.append("amount", count);

            Skyline.API.post("bestand-buchen?material_id="+material_id+"&lager_id="+$("#blager").val(), fd)
                .success(d => {

                    my_table_content_loader();
                })
                .error(err => console.error(err))
                .done(()=>{
                    $("#modal-buchen").modal("hide");
                })
        } else {
            alert("Bitte Materialmenge eingeben.")
            $("#bcount").focus();
        }

        return false;
    }
</script>


<div class="modal fade" id="modal-edit" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modal-title">Material Bearbeiten</h1>
                <button type="button" class="btn-close" onclick="$('#modal-edit').modal('hide')" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form onsubmit="return send_material_changes(this)" id="frm">
                    <input type="hidden" id="material_id" name="material_id" value="0">
                    <div class="mb-3">
                        <label for="lname" class="form-label">Name</label>
                        <input type="text" placeholder="Material" name="name" class="form-control" id="lname" aria-describedby="lname-help">
                        <div id="lname-help" class="form-text">Der Material-Name.</div>
                    </div>
                    <div class="mb-3">
                        <label for="keywords" class="form-label">Schlagworte</label>
                        <input type="text" placeholder="m3 feder verzinkt ..." class="form-control" id="keywords" aria-describedby="lkeywords-help">
                        <div id="lkeywords-help" class="form-text">Schlagworte, getrennt durch Leerzeichen oder Komma.</div>
                    </div>
                    <div class="mb-3">
                        <label for="ldesc" class="form-label">Beschreibung</label>
                        <textarea placeholder="Versuche, wenigstens so zu tun, als ob du das Material beschreibst." name="description" class="form-control" id="ldesc" rows="3"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-primary" onclick="$('#frm').submit()">Speichern</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-buchen" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5">Material Buchen</h1>
                <button type="button" class="btn-close" onclick="$('#modal-buchen').modal('hide')" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form onsubmit="return send_material_buchen(this)" id="frm2">
                    <input type="hidden" id="bmaterial_id" name="material_id" value="0">
                    <div class="mb-3">
                        <label for="bname" class="form-label">Material</label>
                        <input type="text" readonly class="form-control" id="bname">
                    </div>

                    <div class="mb-3">
                        <label for="blager" class="form-label">Lagerort</label>
                        <select class="form-select" id="blager">
                            <?php
                            foreach($LAGERORTE as $record) {
                                printf("<option value=\"%d\">%s</option>", $record['id'], htmlspecialchars( $record['name'] ));
                            }
                            ?>
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="bcount" class="form-label">Menge</label>
                        <input type="number" placeholder="Menge an Material" class="form-control" id="bcount" aria-describedby="bcount-help">
                        <div id="bcount-help" class="form-text">Positive Mengen buchen Material ins Lager ein, negative buchen es aus.</div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-primary" onclick="$('#frm2').submit()">Speichern</button>
            </div>
        </div>
    </div>
</div>