<?php

use Skyline\Render\Context\DefaultRenderContext;
/**
 * @title WLW Projekt :: Lagerorte
 * @description Zeigt alle Lagerorte an
 * @require Application
 *
 * @var DefaultRenderContext $this
 */

?>

<style>
    #tbl-lagerorte tr td.info {
        font-size: 80%;
        color: gray;
        vertical-align: middle;
    }

    #tbl-lagerorte .mat-tools {
        text-align: right;
    }
</style>

<div class="content">
	<h1>Lagerorte</h1>

    <table class="table table-sm table-striped table-hover" id="tbl-lagerorte">
        <thead>
        <tr>
            <th>Lagerort</th>
            <th> </th>
        </tr>
        </thead>
        <tbody>
        <tr class="template">
            <td class="mat-name">Kellerverlies 5A</td>
        </tr>
        </tbody>
    </table>
</div>